### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by BetsabeMP** [Laboratoria/scl-2018-05-bc-core-am-socialnetwork#1]
Datos para benchmark

**Comment by CoteVD** [comment]
Aquí están las aplicaciones que compiten con la nuestra y un breve resúmen de éstas:
1. Parental Click
Quizá una de las apps más recientes, avanzadas y útiles en este sentido. Parental Click permite que los padres puedan vigilar los smartphones de sus hijos de manera segura y controlada. Pero va mucho más allá: en caso de producirse un abuso o agresión, la víctima puede recurrir a la herramienta 'Botón del Fuerte' con la que, agitando el teléfono, activará no sólo el GPS, sino también los programas de grabación de imagen y sonido con la idea de dejar testimonio fehaciente de lo que ha pasado.

Y esa es precisamente su mayor valor añadido: en caso de producirse una situación de acoso, la aplicación genera pruebas (mensajes, amenazas...) que, llegado un posible juicio, cuentan con certificado y validez legal.

2. AppVise
AppVise parte de un concepto algo más amplio. Para empezar, la app cuenta con la tecnología suficiente para que cualquier víctima de acoso pueda notificar la existencia de algún tipo de situación molesta. Sin embargo, va más allá: su herramienta permite establecer canales de comunicación entre padres, profesores y alumnos, además de impulsar talleres que luchen contra cualquier tipo de bullying.

3. Know Bullying (Android / iOS)
Dirigida especialmente a los padres, Know Bullying no sólo permite a los menores informar de posibles casos de abuso, sino que también incide en fomentar la comunicación entre padres e hijos. Por ello, los adultos reciben notificaciones de manera periódica para recordarles la importancia de que se comuniquen con sus hijos a través de la app.

4. StopIt
En este caso, los principales destinatarios son los 'espectadores' del bullying: aquellos alumnos que, ante una situación de ese tipo, prefieren callar o directamente mirar para otro lado.

StopIt les permite que, cuando presencien un tipo de acoso o agresión hacia otra persona, activen la localización, manden un mensaje de socorro e incluso adjunten fotografías o vídeos que puedan servir como prueba.

5. BraveUp
La app busca que la comunidad escolar en su totalidad sea partícipe del proceso formativo de los estudiantes, generando contenidos que son publicados en la plataforma por sus mismos integrantes. Además, se desarrolló el “Modo Brave UP”, que es una función que permite al estudiante que es víctima o testigo de agresión realizar una denuncia de manera confidencial y anónima, potenciando la colaboración y participación.

6. Appvise 
Busca instalarse como una "solución integral" a los conflictos en las escuelas. Es una aplicación que aspira a primero prevenir los casos de bullying y después a actuar en consecuencia, activar un protocolo que vincula a expertos de la empresa con la comunidad educativa. Cuenta con distintas herramientas: una mensajería instantánea que vincula a chicos, profesores y padres, un canal unificado de noticias, una agenda digital y, quizás la más importante, el botón de denuncia.

El botón lo pueden activar tanto los niños como los padres. En un principio se les presenta una serie de preguntas que pretenden determinar si se trata en realidad de bullying o no. Si es así, se prosigue a trabajar con el equipo de orientación y las familias de los niños implicados para resolver el caso. Siempre la denuncia se hace de forma anónima.
